echo "	#Architecture : $(uname -snrvmo)"
echo "	#CPU physical : $(nproc --all)"
echo "	#vCPU : $(cat /proc/cpuinfo | grep processor | wc -l)"
echo "	#Memory Usage : $(free -m | grep Mem | awk '{printf"%d/%dMB (%.2f%%)\n", $3, $2, $3/$2 * 100}')"
echo "	#Disk Usage : $(df -BM -a | grep /dev/mapper | awk '{used+=$3; tot+=($2/1024); per+=$5} END {printf "%dMb/%dGb (%d%%)\n", used, tot, per}')"
echo "	#CPU load : $(mpstat | grep all | awk '{printf "%.2f%%\n", 100-$13}')"
echo "	#Last boot : $(who -b | grep boot | awk '{printf "%s %s\n", $3, $4}')"
echo "	#LVM use : $(if [ "$(lsblk | grep lvm | wc -l)" -eq 0 ]; then printf "no\n"; else printf "yes\n"; fi)"
echo "	#Connexions TCP : $(ss | grep -i tcp | wc -l) ESTABLISHED"
echo "	#User log : $(users | wc -w)"
echo "	#Network : IP $(hostname -I) ($(ip link show | grep link/ether | awk '{print $2}'))"
echo "	#Sudo : $(journalctl _COMM=sudo | grep COMMAND | wc -l) cmd"